# ~/.config/starship.toml

# move the rest of the prompt to the right
right_format = """
$package\
$nodejs\
$cmd_duration"""

# A minimal left prompt
format = """
$os\
$username\
$directory\
$git_branch\
$git_state\
$git_status"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 1000

# Disable the blank line at the start of the prompt
add_newline = false

[os]
disabled = false
format = '[$symbol](bold blue) '

[os.symbols]
Macos = ''

[username]
disabled = false
format = '[$user]($style) '
style_user = 'blue bold'
style_root = 'black bold'
show_always = true

[directory]
disabled = false
format = 'at [$path]($style)[$read_only]($read_only_style) '
truncation_length = 2
truncate_to_repo = false
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '

[cmd_duration]
disabled = false
format = 'took [$duration](bold red)'
min_time = 10

[git_branch]
disabled = false
symbol = ' '
format = 'on [$symbol$branch]($style) '
truncation_symbol = '…/'
style = 'bold green'

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style) '
style = 'yellow'
up_to_date = '[✓](bold yellow) '
conflicted = '[=](bold yellow)[\($count\)](red) '
deleted = '[✘](bold yellow)[\($count\)](red) '
untracked = '[?](bold yellow)[\($count\)](red) '
ahead = '[⇡](bold yellow)[\($count\)](red) '
behind = '[](bold yellow)[\($count\)](red) '
stashed = '[$](bold yellow)[\($count\)](red) '
modified = '[!](bold yellow)[\($count\)](red) '
staged = '[+](bold yellow)[\($count\)](red) '
renamed = '[襁](bold yellow)[\($count\)](red) '
diverged = '[•](bold yellow) '

[git_metrics]
disabled = false

[package]
disabled = false
format = 'is [$symbol$version]($style) '

[nodejs]
disabled = false
format = 'via [$symbol($version )]($style)'

[kubernetes]
disabled = false
format = 'via [󱃾 $context\($namespace\)](bold purple) '

[battery]
disabled = true

[time]
disabled = true
